# Generated by Django 5.2.17 on 2026-09-21 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[("low", "Baixa"), ("medium", "Média"), ("high", "Alta")],
                default="medium",
                max_length=10,
                verbose_name="Prioridade",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Solicitante",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Aberto"),
                    ("in_progress", "Em andamento"),
                    ("resolved", "Resolvido"),
                    ("closed", "Fechado"),
                ],
                default="open",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Título"),
        ),
    ]
