# Generated by Django 5.2.17 on 2026-09-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_two_factor_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Sem 2FA, uma senha vazada ou reaproveitada de outro site já é suficiente para tomar esta conta — não é um risco hipotético, é o vetor de invasão mais comum. Esta flag só reflete se o usuário terminou a configuração; ative em 'Segurança da conta' após o primeiro login (aplicativo autenticador ou e-mail).",
            ),
        ),
    ]
