# Generated by Django 5.2.17 on 2026-09-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_backfill_owner_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Administrador"),
                    ("admin", "Administrador"),
                    ("support", "Suporte"),
                    ("user", "Usuário"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
